### ISSUE TITLE
PS3 Eye driver error: Unknown Error

### ISSUE THREAD

**Issue by gabrielwong1991** [opentrack/opentrack#1495]
Hi earlier today Opentrack works fine but when i hibernate the computer and come back I can't start opentrack anymore. It saids `PS3 Eye driver error: Unknown Error`. The camera red light flashes a bit but would not turn on...

I tried reinstalling opentrack but problem still exists.

The CL-eye test driver works fine so anywhere I could check what causes the problem? Thanks

![image](https://user-images.githubusercontent.com/30657000/172972071-0982a3af-39a7-4694-9a66-109775f9251e.png)

**Comment by gabrielwong1991** [comment]
If anyone is having problem I need to change the driver back to `PS3Eye Camera`. `PS3 Eye open driver` is giving me problem.

Thanks all!

**Comment by RedCondor6** [comment]
Also having this problem, any input appreciated!

**Comment by RedCondor6** [comment]
> Also having this problem for a while now. Months.

I have reverted back to using the old CL-Eye driver, if you need a copy let me know.

**Comment by RedCondor6** [comment]
I sent you an email with the link! See you in the skies 👍

**Comment by JonathonCoughlin** [comment]
> I sent you an email with the link! See you in the skies 👍

I got it; thank you!

**Comment by JDeeth** [comment]
I got the same error just now - it worked fine yesterday. The difference is that when I shut down the PC yesterday it installed a Windows update.

**Comment by Dominik2414** [comment]
hello i have the same problem does anyone know what to do?

**Comment by RedCondor6** [comment]
> hello i have the same problem does anyone know what to do?

If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍

**Comment by lennykleinesau** [comment]
> RedCondor6

Hello can you send me the old version? thank you email is: jonischmu@gmail.com

**Comment by RedCondor6** [comment]
Sent 👍

**Comment by JDeeth** [comment]
I've had this problem twice now, and I _think_ this is a fix:
1. occurs just after a Windows update / Windows security update
2. reinstall the camera driver - from libUsbK to somethin/ else then back again
3. plug camera into a different USB port - some of mine seem flaky, and it's suspected it's those which are run via the CPU not the chipset, or possibly vice versa
4. rub the camera with garlic in the light of a full moon while restarting the PC

**Comment by michaelosthege** [comment]
Another reason (at least on my machine) can be interference with [_WinUsbDisplay_/_MS USB Display_](https://github.com/MindShow/USBDisplay) which I need for two USB/HDMI adapters for my MFD screens.

I have not yet tried all permutations of
* switching USB ports
* turning on the cam in opentrack
* starting _MS USB Display_

... but so far it looks like starting the cam in opentrack before starting the _MS USB Display_ thing got me into a state where all things were working at the same time.

**Comment by egolgeli** [comment]
> > hello i have the same problem does anyone know what to do?
> 
> If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍



> > hello i have the same problem does anyone know what to do?
> 
> If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍

Hi. Possible to send a copy of CL Eye Driver to me too? egolgeli@yahoo.com. Thanks a lot.

**Comment by RedCondor6** [comment]
> > > hello i have the same problem does anyone know what to do?
> > 
> > 
> > If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍
> 
> > > hello i have the same problem does anyone know what to do?
> > 
> > 
> > If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍
> 
> Hi. Possible to send a copy of CL Eye Driver to me too? [egolgeli@yahoo.com](mailto:egolgeli@yahoo.com). Thanks a lot.

Hi, I've just sent you a copy of it! Happy flying.

**Comment by Jabzzo** [comment]
> > > > hello i have the same problem does anyone know what to do?
> > > 
> > > 
> > > If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍
> > 
> > 
> > > > hello i have the same problem does anyone know what to do?
> > > 
> > > 
> > > If you would like me to send you a copy of the CL eye driver let me know, I'll need your email if so 👍
> > 
> > 
> > Hi. Possible to send a copy of CL Eye Driver to me too? [egolgeli@yahoo.com](mailto:egolgeli@yahoo.com). Thanks a lot.
> 
> Hi, I've just sent you a copy of it! Happy flying.

Hi can you send me the link please? Jacobdallen2007@gmail.com

**Comment by Aynthem** [comment]
Could either of you send me the old driver. I am having the same issue. Literally made an account when I found this answer. 
Aynthem@protonmail.com

**Comment by RedCondor6** [comment]
> Could either of you send me the old driver. I am having the same issue. Literally made an account when I found this answer. [Aynthem@protonmail.com](mailto:Aynthem@protonmail.com)

Sent 👍

**Comment by Aynthem** [comment]
### PS3 Camera IR Longpass Filter and Removable Rubber Sleeve

I will share this here. I decided making a sleeve for my PS3 eye camera would be best. I tried using floppy disk film, clear plastic colored black, and stacking lenses but nothing worked better than this for blocking unwanted light and ease of use. I went to Home Depot and bought a 7/8" (NOT the 1") rubber bottom for a chair. They sell them in a 4 pack for a few bucks. I cut off ~ 1/4 inch from the the length of the tube in which you would place the leg of the chair. I then cut off the convex bottom (the part that would go on the floor) and sanded it flat. The bottom, once flat, will be about 1-1/4" because it tapers. I drilled/cut a 7/8 hole in the center for the lense (at this point you can look through it like a pipe). Then I used a Dremel tool with a sanding bit to create a 1" lip. I cleaned the entire rubber piece with rubbing alcohol to remove dust and debris. Inside this lip I carefully set and superglued a 1" diameter Edmunds Optics plastic infared long pass filter that I got on eBay for $3. It filters out wavelengths under 1K nm I believe. I clamped it (WITH A FILM OVER THE LENSE FOR PROTECTION!!!) while it set/dried and it worked like a charm. Even bright lights can be overcome with some tuning in opentrack. My current settings are: Min Size: 2.5, Max Size 6.0, Brightness: 15/255, Gain: 12, and Exposure: 200. This is with the FLAT lense "Bad" camera mind you. I have the "Good" camera on its way. I expect the performance to increase significantly. The sleeve is easily applied and removed, sliding on/off of the lense.

![387549621_289294203907524_7362694761336522454_n](https://github.com/opentrack/opentrack/assets/147895129/a833eeae-8c54-4a8a-80c0-5c9712d66a47)

![370242304_850721763172718_2511646777791141817_n](https://github.com/opentrack/opentrack/assets/147895129/ab0b555c-d540-45f9-b7b4-72d0c3dc166a)

![370198886_337033822152659_5483671937821805339_n](https://github.com/opentrack/opentrack/assets/147895129/c5899ae5-1398-4b46-8639-23302ca41a56)

![387523939_270359429323615_4459929608622448007_n](https://github.com/opentrack/opentrack/assets/147895129/877291b9-db48-4dd5-9e8c-0e9c78a76280)

![368437331_293607750292569_8650746980867312025_n](https://github.com/opentrack/opentrack/assets/147895129/7c3ec4f0-ef5f-4567-b658-425e72469e71)

![image](https://github.com/opentrack/opentrack/assets/147895129/13919652-c16f-4e7d-87a3-645637fe1507)

**Comment by 12gabriel3** [comment]
I am using libusb driver and my camera started having this error all of a sudden. I changed the USB port but it did not work. I also tried to reset libusb driver to no avail. This is how I fixed it:

1. Open device manager
2. Scroll to Universal Serial Bus Controllers
3. See if there is any unrecognized device and uninstall it

**Comment by ericrisler** [comment]
> I am using libusb driver and my camera started having this error all of a sudden. I changed the USB port but it did not work. I also tried to reset libusb driver to no avail. This is how I fixed it:
> 
> 1. Open device manager
> 2. Scroll to Universal Serial Bus Controllers
> 3. See if there is any unrecognized device and uninstall it

This worked for me as well - seems really odd. Anyone know why this might be?

**Comment by Gorrex666** [comment]
> 3. plug camera into a different USB port - some of mine seem flaky, and it's suspected it's those which are run via the CPU not the chipset, or possibly vice versa


this fixed it for me. For some reason the top usb ports were giving me OP error but the ones in the middle of the MB worked fine.

**Comment by Aquanoss** [comment]
Hi yall. I used Zadig to install the driver onto my ps3 eye, but its still not WCID compatible
