### ISSUE TITLE
Tracking lags a lot when recording/streaming with any software

### ISSUE THREAD

**Issue by gienkov** [opentrack/opentrack#271]
As stated in title, I experience very annoying issue with OT. Basically I cannot record or stream when I have tracking active. Game FPS are ok but tracker jitters to a point where I start to have headache.
You can see what I mean on my yesterday stream here:
https://youtu.be/CvBvlpotdgo?t=81

**Comment by sthalik** [comment]
How many CPU cores? How many cores encoding takes? Tracker used?

**Comment by gienkov** [comment]
4 cores, point tracker, x264 encoder.

**Comment by sthalik** [comment]
How many cores does ED use? How many does encoding use? Can this be solved by adjusting opentrack priority to realtime?

**Comment by sthalik** [comment]
@gienkov update to rc21p2. There was a runaway thread consuming one core since p19, now fixed.

**Comment by gienkov** [comment]
Zabieram się za testy ;)

**Comment by gienkov** [comment]
It seems somewhat better now, but jitter is still existent. I have way more smooth input when I'm not recording than when I do.

**Comment by sthalik** [comment]
Set opentrack to realtime priority in Windows task manager. There are likely not enough cycles for it.

**Comment by koreldan** [comment]
I've had the same problem.
I solved changing filter from "Accela" to "EWMA"

I use OpenTrack with the EDTracker Pro & OpenTrack v2.3 rc21p2

**Comment by gienkov** [comment]
I'l try EWMA then, testing in few mins

**Comment by HornetMaX** [comment]
I have an EDTracker Pro too and I don't need any filter at all in OpenTrack. What's the need ?

**Comment by koreldan** [comment]
It flicker a little to me, maybe because it has too much sensitivity... dunno

i've set "pitch scaling" and "yaw scaling" to 1, "smoothing" to 99 and "response mode" to linear.

Any tips ?

**Comment by HornetMaX** [comment]
Weird. I have mine with pitch and yaw scaling at 1, smoothing at 50 and no filter in opentrack, zero problems.

**Comment by koreldan** [comment]
Maybe i should re-calibrate the magnetometer ?

**Comment by HornetMaX** [comment]
Could help. Also remember to keep the EDTracker still the first 20sec you power it up, as it does a bias compensation each time.

**Comment by koreldan** [comment]
sometimes after the 20sec i click on "auto bias" to be sure that it will be somehow more stable

**Comment by HornetMaX** [comment]
Same here, I just hate the auto auto-bias at startup.

**Comment by koreldan** [comment]
I was used to use a self-made headtracker with 4 leds hat + a crappy webcam... it worked pretty well but the "EDTracker Pro" experience is pure gold to me ;)

**Comment by HornetMaX** [comment]
Yeah, EDtracker rocks. I'm really waiting for their wireless version. OK, back on topic now :)

**Comment by koreldan** [comment]
I've just realized that you are the author of OpenTrack... awesome work, man !

**Comment by HornetMaX** [comment]
Me ? I'm definitely not ! sthalik is.
I didn't even contribute a single line :)

**Comment by sthalik** [comment]
If it works in EWMA but jumps around in Accela, it's definitely a but in Accela. We should get to the bottom of this rather than to prescribe workarounds.

**Comment by HornetMaX** [comment]
Sure, I agree. Was just surprised of the need of a filter with an EDTracker.
Of course there are other devices that do need a filter, so it should work (or be made to).

**Comment by koreldan** [comment]
it doesn't jump around.... it flickers a little with the accela filter.

Anyway, I've removed also the filters and re-calibrated the tracker and followed some suggestion provided by HornetMaX.

sthalik, I'm sorry for my wrong attribution of the project... and thank you for your effort on keeping the software working. great work  ! ;)

**Comment by sthalik** [comment]
To diagnose the issue with Accela, I already asked you to adjust process priority and see if it still occurs. I can't help you if you won't help me diagnose the issue.

**Comment by koreldan** [comment]
sorry... I'll try tomorrow

**Comment by sthalik** [comment]
If issue still occurs with realtime priority, compare game fps when encoding and not encoding.

**Comment by koreldan** [comment]
ok.
Acella seems fixed with version opentrack-2.3 rc21p4

I've also tried with opentrack-2.3 rc21p2 ... that version still has problems with acella.

By the way... last release fixed acella problems... no process changes needed ;)

**Comment by sthalik** [comment]
@gienkov are there any issues left here?

**Comment by sthalik** [comment]
I'm closing this. Please comment if there are any more issues.
